FROM ubuntu:22.04

# Install dependencies
RUN apt update \
 && apt install --yes --no-install-recommends git cmake build-essential ca-certificates ninja-build clang lld python3.10-dev pip
RUN git clone https://github.com/xdslproject/xdsl.git \
 && git clone https://github.com/devitocodes/devito.git \
 && git clone https://github.com/llvm/llvm-project.git
RUN cd llvm-project \
 && git checkout 89996621de073e43de7bed552037b10d2a0fdf80
RUN mkdir llvm-project/build \
 && cd llvm-project/build \
 && cmake -G Ninja ../llvm -DLLVM_ENABLE_PROJECTS="mlir;clang;openmp" -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=OFF -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_LLD=ON
RUN cd llvm-project/build \
 && cmake --build . --target install
RUN cd xdsl \
 && pip install -r requirements.txt .
RUN cd devito \
 && pip install -r requirements.txt .
