# This workflow will install MLIR, Python dependencies, run tests and lint with a single version of Python
# File inherited from https://github.com/xdslproject/xdsl/blob/main/.github/workflows/ci-mlir.yml

name: CI - MLIR-based Testing for MPI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: gbisbas/xdsl-llvm:0.1
    steps:
    - name: Checkout Devito
      uses: actions/checkout@v3

    - name: Install native dependencies
      run: |
        apt install -y curl mpich

    - name: Upgrade pip
      run: |
        pip install --upgrade pip

    - name: Install requirements and xDSL
      run: |
        pip install -e .[tests]
        pip install mpi4py
        pip install xdsl==0.14

    - name: Test with MPI
      run: |
        # Add mlir-opt to the path
        export PATH=/xdsl-sc/llvm-project/build/bin/:$PATH
        pytest -m "parallel" -k "not adjoint" tests/