name: Publish to PyPI
on: push
jobs:
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install wheel
      run: >-
        python -m pip install wheel --user
    - name: Build a binary wheel and source package in dist/
      run: >-
        python setup.py sdist bdist_wheel
    - name: Publish distribution to fake Test PyPI repo
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
        # publish to the test PyPI repository instead like this:
        # (you'll need to create an API token at test.pypi.org)
        # password: ${{ secrets.test_pypi_password }}
        # repository_url: https://test.pypi.org/legacy/
