name: Publish to PyPI
on: push
jobs:
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build a binary wheel and source package in dist/
      run: >-
        python setup.py sdist bdist_wheel
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
