name: CI-core

permissions:
  contents: read

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - debug-data-failuer

jobs:
  test-nompi-basic:
    name: pytest-ubuntu-py311-gcc10-noomp-base
    runs-on: ubuntu-latest

    env:
      DEVITO_ARCH: "gcc"
      DEVITO_LANGUAGE: "C"
      OMP_NUM_THREADS: 2

    strategy:
      # Prevent cancellation if a single workflow fails
      fail-fast: false

    steps:
    - name: Checkout devito
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.11
        allow-prereleases: true

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -e ".[tests,extras]"

    - name: Install GDB
      run: |
        sudo apt-get update
        sudo apt-get install -y gdb

    - name: Run debug script
      run: |
        chmod +x debug_mem.sh
        ./debug_mem.sh
