name: CI-mpi

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-mpi-basic:
    name: pytest-mpi
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    env:
      DEVITO_LANGUAGE: "openmp"
      DEVITO_ARCH: "gcc"
      OMP_NUM_THREADS: "1"
      RDMAV_FORK_SAFE: 1

    steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout devito
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt install mpich -y
        pip3 install --upgrade pip
        pip3 install -e ".[extras,mpi,tests]" --no-binary=mpi4py

    - name: Test with pytest
      run: |
        python3 scripts/clear_devito_cache.py
        python3 -m pytest --cov --cov-config=.coveragerc --cov-report=xml -m parallel tests/

    - name: Test examples with MPI
      run: |
        python3 scripts/clear_devito_cache.py
        DEVITO_MPI=1 mpirun -n 2 python3 -m pytest examples/seismic/acoustic
        DEVITO_MPI=1 mpirun -n 2 python3 -m pytest examples/seismic/tti

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: pytest-mpi

  test-mpi-docker:
    name: pytest-mpi
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          pytest-mpi-docker-gcc,
          pytest-mpi-docker-gcc-arm,
          pytest-mpi-docker-icx
        ]
        include:
        - name: pytest-mpi-docker-gcc
          arch: gcc
          os: ubuntu-latest

        - name: pytest-mpi-docker-gcc-arm
          arch: gcc
          os: ubuntu-24.04-arm

        - name: pytest-mpi-docker-icx
          arch: icx
          os: ubuntu-latest

    steps:
    - name: Checkout devito
      uses: actions/checkout@v6

    - id: build
      name: Build docker image
      uses: ./.github/actions/docker-build
      with:
        file: docker/Dockerfile.devito
        tag: ${{ matrix.name }}
        base: devitocodes/bases:cpu-${{ matrix.arch }}

    - name: Test with pytest
      uses: ./.github/actions/docker-run
      with:
        uid: ${{ steps.build.outputs.unique }}
        tag: ${{ matrix.name }}
        env: |
          CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
          OMP_NUM_THREADS=1
        command: "pytest tests/test_mpi.py"

    - name: Test acoustic example with MPI
      uses: ./.github/actions/docker-run
      with:
        uid: ${{ steps.build.outputs.unique }}
        tag: ${{ matrix.name }}
        env: |
          DEVITO_MPI=1
          OMP_NUM_THREADS=1
        command: "mpiexec -n 2 pytest examples/seismic/acoustic"

    - name: Test tti example with MPI
      uses: ./.github/actions/docker-run
      with:
        uid: ${{ steps.build.outputs.unique }}
        tag: ${{ matrix.name }}
        env: |
          DEVITO_MPI=1
          OMP_NUM_THREADS=1
        command: "mpiexec -n 2 pytest examples/seismic/tti"

    - name: Cleanup docker image
      if: always()
      uses: ./.github/actions/docker-clean
      with:
        uid: ${{ steps.build.outputs.unique }}
        tag: ${{ matrix.name }}
